# fly.toml app configuration file generated for halolight-api-node on 2025-12-10
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'halolight-api-node'
primary_region = 'iad'

[build]

[deploy]
  release_command = "pnpm prisma migrate deploy"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.checks]
    [http_service.checks.http]
      path = "/health"
      interval = "30s"
      timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
